{
  "id": "codex-hooks",
  "name": "Codex Hooks Contract",
  "version": "1.0.0",
  "owners": ["{{HARNESS_REPO_NAME}}"],
  "affectedRepos": ["{{HARNESS_REPO_NAME}}"],
  "requiredFiles": [
    ".codex/hooks.json",
    "scripts/hooks/codex-hook.mjs",
    "scripts/hooks/lib/codex-hooks-core.mjs",
    "ai/contracts/codex-hooks.md"
  ],
  "forbiddenTokens": [
    "fetch(",
    "writeFile(",
    "appendFile(",
    "chmod(",
    "chown(",
    "copyFile(",
    "cp(",
    "fchmod(",
    "fchown(",
    "fdatasync(",
    "fsync(",
    "ftruncate(",
    "futimes(",
    "lchmod(",
    "lchown(",
    "link(",
    "lutimes(",
    "mkdir(",
    "mkdtemp(",
    "rename(",
    "rm(",
    "rmdir(",
    "symlink(",
    "truncate(",
    "unlink(",
    "utimes(",
    "writev(",
    "writeFileSync",
    "appendFileSync",
    "chmodSync",
    "chownSync",
    "copyFileSync",
    "cpSync",
    "fchmodSync",
    "fchownSync",
    "fdatasyncSync",
    "fsyncSync",
    "ftruncateSync",
    "futimesSync",
    "lchmodSync",
    "lchownSync",
    "linkSync",
    "lutimesSync",
    "mkdirSync",
    "mkdtempSync",
    "renameSync",
    "rmSync",
    "rmdirSync",
    "symlinkSync",
    "truncateSync",
    "unlinkSync",
    "utimesSync",
    "writeSync",
    "writevSync",
    "createWriteStream",
    "openSync(write flags)"
  ],
  "validation": ["node scripts/check-codex-hooks.mjs"]
}
